// <auto-generated />
using BlazorWebAssemblyCrudDotNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWebAssemblyCrudDotNet.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240305123225_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorWebAssemblyCrudDotNet8.Shared.Entities.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Registration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ranvijay@gmail.com",
                            Image = new byte[0],
                            Name = "Ranvijay",
                            OTP = "123456",
                            Password = "ranvijary",
                            Username = "ranvijay1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ramu@gmail.com",
                            Image = new byte[0],
                            Name = "Ramu",
                            OTP = "654321",
                            Password = "ramu",
                            Username = "ramu2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "shamu@gmail.com",
                            Image = new byte[0],
                            Name = "Shamu",
                            OTP = "987654",
                            Password = "shamu",
                            Username = "shamu3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
